name: 'chess_com_bi_pg'
version: '1.0.0'

profile: 'chess_com_bi_pg'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"

models:
  chess_com_bi_pg:
    intermediate:
      +schema: int
      +materialized: table
    datawarehouse:
      +schema: dwh
      +materialized: table
seeds:
  chess_com_bi_pg:
    +schema: stg_seeds

vars:
  data_conversion:
    utc_to_target_timezone: "'Europe/Paris'"
  game_phases:
      early:
        end_game_move: 15
        name: "'1-Early Game'"
      mid: 
        end_game_move: 35
        name: "'2-Mid Game'"
      late: 
        end_game_move: 65
        name: "'3-Late Game'"
      very_late:
        name: "'4-Very Late Game'"

  elo_range: [400,600,800,1000,1200,1400,1600,1800]
  score_thresholds:
    variance_score_massive_blunder: 600
    variance_score_blunder: 250
    variance_score_mistake: 100
    score_balanced_limit: 200
    even_score_limit: 150
  should_win_range:
    low: 300
    mid: 500
  data_scope:
    month_history_depth: 12
    time_class: ['blitz', 'rapid', 'bullet']
  datamart:
    min_games_played: 20