name: 'chess_com_bi_pg'
version: '1.0.0'

profile: 'chess_com_bi_pg'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"

models:
  chess_com_bi_pg:
    +meta:
      doc_info: "Column-level documentation is maintained only for the staging (stg) and core marts (dim/fct) layers. For any column definition, refer to those models as the source of truth."
    staging:
      +schema: stg
      +materialized: view
      +docs:
        node_color: '#498D1C' # Darker green than seeds
    intermediate:
      +schema: int
      +materialized: table
      +docs:
        node_color: '#696969' # Silver
    marts:
      +schema: marts
      +materialized: table
      analytics:
        +docs:
          node_color: '#C57B39' # Darker gold
      core:
        +docs:
          node_color: '#C5A939' # Gold
  dbt_project_evaluator:
      +schema: eval
      marts:
        +enabled: false
        core:
          +enabled: true
        structure:
          +enabled: true
        performance:
          +enabled: true
        dag:
          +enabled: true 
        documentation:
          +enabled: true
        governance:
          +enabled: true
        tests:
          +enabled: true
          fct_sources_without_freshness: # Expects all sources to have freshness tests - not needed for now since freshness is managed via heathchecks.
            +enabled: false
          fct_missing_primary_key_tests: # Expects all models to have primary key tests - not needed for all models, already done for the riskiest ones.
            +enabled: false

seeds:
  chess_com_bi_pg:
    +schema: raw_seeds
    +docs:
      node_color: '#5fb825' # Light Green (like DBT sources)
tests:
  chess_com_bi_pg:
    +docs:
      node_color: "#FF0000" # Red
  dbt_project_evaluator:
    +severity: error

dispatch:
  - macro_namespace: dbt
    search_order: ['dbt_project_evaluator', 'dbt']

vars:
  data_conversion:
    utc_to_target_timezone: "'Europe/Paris'"
  game_phases:
      early:
        end_game_move: 15
        name: "'1-Early Game'"
      mid: 
        end_game_move: 35
        name: "'2-Mid Game'"
      late: 
        end_game_move: 65
        name: "'3-Late Game'"
      very_late:
        name: "'4-Very Late Game'"
  dbt_project_evaluator:
    model_types: ['staging', 'intermediate', 'marts', 'other']
    marts_prefixes: ['obt_', 'dim_', 'fct_']
    test_coverage_target: 25 # No need to have as many tests as models. We value quality over quantity.
  move_stats_snapshots: [5,10,15,20,25,30,35,40,45,50]
  elo_range: [400,600,800,1000,1200,1400,1600,1800]
  score_thresholds:
    variance_score_massive_blunder: 600
    variance_score_blunder: 250
    variance_score_mistake: 100
    score_balanced_limit: 200
    even_score_limit: 150
  should_win_range:
    low: 300
    mid: 500
  data_scope:
    month_history_depth: 12
    time_class: ['blitz', 'rapid', 'bullet']
  openings:
    hierarchy_depth: 10
