version: 2

sources:
  - name: chess_com
    description: "Raw data ingested from the chess.com API"
    schema: stg_chess_com
    tables:
      - name: players_games
        description: "chess.com games played"
        
  - name: stockfish
    description: "Raw data calculated by Stockfish for each game and move"
    schema: stg_stockfish
    tables: 
      - name: players_games_moves
        description: "Stockfish calculated moves"

  - name: times
    description: "Raw data calculated with Python to extract durations for each game and move"
    schema: stg_times
    tables: 
      - name: players_games_times
        description: "Python calculated move durations"