{{ config(
    materialized = 'incremental',
    incremental_strategy = 'append',
    post_hook=[
        "CREATE INDEX IF NOT EXISTS idx_{{ this.name }}_log_timestamp ON {{ this }} (log_timestamp)"
    ]
) }}

SELECT
    {{ dbt_utils.generate_surrogate_key(['gs.username']) }} AS players_sk,
    {{ dbt_utils.generate_surrogate_key(['gs.uuid', 'gs.username']) }} AS games_sk,
    gs.username,
    gs.uuid,
    gs.log_timestamp,
    gs.nb_moves,
    gs.nb_blunder_massive_blunder_playing,
    gs.nb_massive_blunder_playing,
    gs.nb_moves_above_decisive_advantage,
    gs.massive_blunder_move_number_playing,
    gs.nb_throw_playing,
    gs.nb_throw_blunder_playing,
    gs.nb_throw_massive_blunder_playing,
    gs.nb_missed_opportunity_playing,
    gs.nb_missed_opportunity_blunder_playing,
    gs.nb_missed_opportunity_massive_blunder_playing,
    gs.nb_massive_blunder_playing_early,
    gs.nb_blunder_massive_blunder_playing_early,
    gs.nb_missed_opportunity_blunder_playing_early,
    gs.nb_missed_opportunity_massive_blunder_playing_early,
    gs.nb_throw_blunder_playing_early,
    gs.nb_throw_massive_blunder_playing_early,
    gs.nb_massive_blunder_playing_mid,
    gs.nb_blunder_massive_blunder_playing_mid,
    gs.nb_missed_opportunity_blunder_playing_mid,
    gs.nb_missed_opportunity_massive_blunder_playing_mid,
    gs.nb_throw_blunder_playing_mid,
    gs.nb_throw_massive_blunder_playing_mid,
    gs.nb_massive_blunder_playing_late,
    gs.nb_blunder_massive_blunder_playing_late,
    gs.nb_missed_opportunity_blunder_playing_late,
    gs.nb_missed_opportunity_massive_blunder_playing_late,
    gs.nb_throw_blunder_playing_late,
    gs.nb_throw_massive_blunder_playing_late,
    gs.nb_massive_blunder_playing_very_late,
    gs.nb_blunder_massive_blunder_playing_very_late,
    gs.nb_missed_opportunity_blunder_playing_very_late,
    gs.nb_missed_opportunity_massive_blunder_playing_very_late,
    gs.nb_throw_blunder_playing_very_late,
    gs.nb_throw_massive_blunder_playing_very_late,
    gs.nb_throw_opponent,
    gs.nb_throw_blunder_opponent,
    gs.nb_throw_massive_blunder_opponent,
    gs.nb_missed_opportunity_opponent,
    gs.nb_missed_opportunity_blunder_opponent,
    gs.nb_missed_opportunity_massive_blunder_opponent,
    gs.nb_massive_blunder_opponent_early,
    gs.nb_blunder_massive_blunder_opponent_early,
    gs.nb_missed_opportunity_blunder_opponent_early,
    gs.nb_missed_opportunity_massive_blunder_opponent_early,
    gs.nb_throw_blunder_opponent_early,
    gs.nb_throw_massive_blunder_opponent_early,
    gs.nb_massive_blunder_opponent_mid,
    gs.nb_blunder_massive_blunder_opponent_mid,
    gs.nb_missed_opportunity_blunder_opponent_mid,
    gs.nb_missed_opportunity_massive_blunder_opponent_mid,
    gs.nb_throw_blunder_opponent_mid,
    gs.nb_throw_massive_blunder_opponent_mid,
    gs.nb_massive_blunder_opponent_late,
    gs.nb_blunder_massive_blunder_opponent_late,
    gs.nb_missed_opportunity_blunder_opponent_late,
    gs.nb_missed_opportunity_massive_blunder_opponent_late,
    gs.nb_throw_blunder_opponent_late,
    gs.nb_throw_massive_blunder_opponent_late,
    gs.nb_massive_blunder_opponent_very_late,
    gs.nb_blunder_massive_blunder_opponent_very_late,
    gs.nb_missed_opportunity_blunder_opponent_very_late,
    gs.nb_missed_opportunity_massive_blunder_opponent_very_late,
    gs.nb_throw_blunder_opponent_very_late,
    gs.nb_throw_massive_blunder_opponent_very_late,
    gs.first_blunder_massive_blunder_playing_prct_time_remaining,
    gs.first_massive_blunder_playing_prct_time_remaining,
    gs.first_missed_opp_massive_blunder_playing_prct_time_remaining,
    gs.first_throw_massive_blunder_playing_prct_time_remaining,
    gs.prct_time_remaining_playing_early,
    gs.prct_time_remaining_playing_mid,
    gs.prct_time_remaining_playing_late,
    gs.median_score_playing,
    gs.max_score_playing,
    gs.min_score_playing,
    gs.std_score_playing,
    gs.max_score_playing_range,
    gs.max_score_playing_type,
    gs.has_throw_blunder_playing,
    gs.has_throw_blunder_playing_early,
    gs.has_throw_blunder_playing_mid,
    gs.has_throw_blunder_playing_late,
    gs.has_throw_massive_blunder_playing,
    gs.has_throw_massive_blunder_playing_early,
    gs.has_throw_massive_blunder_playing_mid,
    gs.has_throw_massive_blunder_playing_late,
    gs.has_missed_opportunity_blunder_playing,
    gs.has_missed_opportunity_blunder_playing_early,
    gs.has_missed_opportunity_blunder_playing_mid,
    gs.has_missed_opportunity_blunder_playing_late,
    gs.has_missed_opportunity_massive_blunder_playing,
    gs.has_missed_opportunity_massive_blunder_playing_early,
    gs.has_missed_opportunity_massive_blunder_playing_mid,
    gs.has_missed_opportunity_massive_blunder_playing_late
FROM {{ ref('int_games_stats') }} gs
{% if is_incremental() %}
    WHERE gs.log_timestamp > (
        SELECT MAX(i.log_timestamp)
        FROM {{ this }} i
    )
{% endif %}