{{ config(
    materialized = 'incremental',
    incremental_strategy = 'append',
    post_hook = [
        "CREATE INDEX IF NOT EXISTS idx_{{ this.name }}_run_timestamp ON {{ this }} (run_timestamp)"
    ]
) }}

SELECT
    {{ dbt_utils.generate_surrogate_key(['gs.username']) }} AS players_sk,
    {{ dbt_utils.generate_surrogate_key(['gs.uuid', 'gs.username']) }} AS games_sk,
    gs.username,
    gs.uuid,
    gs.run_timestamp,
    gs.nb_moves,
    gs.nb_blunder_big_blunder_playing,
    gs.nb_big_blunder_playing,
    gs.nb_moves_above_decisive_advantage,
    gs.score_playing_turn_5,
    gs.score_playing_turn_10,
    gs.score_playing_turn_15,
    gs.score_playing_turn_20,
    gs.score_playing_turn_25,
    gs.score_playing_turn_30,
    gs.score_playing_turn_35,
    gs.score_playing_turn_40,
    gs.score_playing_turn_45,
    gs.score_playing_turn_50,
    gs.big_blunder_move_number_playing,
    gs.nb_throw_playing,
    gs.nb_throw_blunder_playing,
    gs.nb_throw_big_blunder_playing,
    gs.nb_miss_opp_playing,
    gs.nb_miss_opp_blunder_playing,
    gs.nb_miss_opp_big_blunder_playing,
    gs.nb_big_blunder_playing_early,
    gs.nb_blunder_big_blunder_playing_early,
    gs.nb_miss_opp_blunder_playing_early,
    gs.nb_miss_opp_big_blunder_playing_early,
    gs.nb_throw_blunder_playing_early,
    gs.nb_throw_big_blunder_playing_early,
    gs.nb_big_blunder_playing_mid,
    gs.nb_blunder_big_blunder_playing_mid,
    gs.nb_miss_opp_blunder_playing_mid,
    gs.nb_miss_opp_big_blunder_playing_mid,
    gs.nb_throw_blunder_playing_mid,
    gs.nb_throw_big_blunder_playing_mid,
    gs.nb_big_blunder_playing_late,
    gs.nb_blunder_big_blunder_playing_late,
    gs.nb_miss_opp_blunder_playing_late,
    gs.nb_miss_opp_big_blunder_playing_late,
    gs.nb_throw_blunder_playing_late,
    gs.nb_throw_big_blunder_playing_late,
    gs.nb_big_blunder_playing_very_late,
    gs.nb_blunder_big_blunder_playing_very_late,
    gs.nb_miss_opp_blunder_playing_very_late,
    gs.nb_miss_opp_big_blunder_playing_very_late,
    gs.nb_throw_blunder_playing_very_late,
    gs.nb_throw_big_blunder_playing_very_late,
    gs.nb_throw_opponent,
    gs.nb_throw_blunder_opponent,
    gs.nb_throw_big_blunder_opponent,
    gs.nb_miss_opp_opponent,
    gs.nb_miss_opp_blunder_opponent,
    gs.nb_miss_opp_big_blunder_opponent,
    gs.nb_big_blunder_opponent_early,
    gs.nb_blunder_big_blunder_opponent_early,
    gs.nb_miss_opp_blunder_opponent_early,
    gs.nb_miss_opp_big_blunder_opponent_early,
    gs.nb_throw_blunder_opponent_early,
    gs.nb_throw_big_blunder_opponent_early,
    gs.nb_big_blunder_opponent_mid,
    gs.nb_blunder_big_blunder_opponent_mid,
    gs.nb_miss_opp_blunder_opponent_mid,
    gs.nb_miss_opp_big_blunder_opponent_mid,
    gs.nb_throw_blunder_opponent_mid,
    gs.nb_throw_big_blunder_opponent_mid,
    gs.nb_big_blunder_opponent_late,
    gs.nb_blunder_big_blunder_opponent_late,
    gs.nb_miss_opp_blunder_opponent_late,
    gs.nb_miss_opp_big_blunder_opponent_late,
    gs.nb_throw_blunder_opponent_late,
    gs.nb_throw_big_blunder_opponent_late,
    gs.nb_big_blunder_opponent_very_late,
    gs.nb_blunder_big_blunder_opponent_very_late,
    gs.nb_miss_opp_blunder_opponent_very_late,
    gs.nb_miss_opp_big_blunder_opponent_very_late,
    gs.nb_throw_blunder_opponent_very_late,
    gs.nb_throw_big_blunder_opponent_very_late,
    gs.first_blunder_big_blunder_playing_prct_time_remaining,
    gs.first_big_blunder_playing_prct_time_remaining,
    gs.first_missed_opp_big_blunder_playing_prct_time_remaining,
    gs.first_throw_big_blunder_playing_prct_time_remaining,
    gs.prct_time_remaining_playing_early,
    gs.prct_time_remaining_playing_mid,
    gs.prct_time_remaining_playing_late,
    gs.median_score_playing,
    gs.max_score_playing,
    gs.min_score_playing,
    gs.std_score_playing,
    gs.max_score_playing_range,
    gs.max_score_playing_type,
    gs.has_throw_blunder_playing,
    gs.has_throw_blunder_playing_early,
    gs.has_throw_blunder_playing_mid,
    gs.has_throw_blunder_playing_late,
    gs.has_throw_big_blunder_playing,
    gs.has_throw_big_blunder_playing_early,
    gs.has_throw_big_blunder_playing_mid,
    gs.has_throw_big_blunder_playing_late,
    gs.has_miss_opp_blunder_playing,
    gs.has_miss_opp_blunder_playing_early,
    gs.has_miss_opp_blunder_playing_mid,
    gs.has_miss_opp_blunder_playing_late,
    gs.has_miss_opp_big_blunder_playing,
    gs.has_miss_opp_big_blunder_playing_early,
    gs.has_miss_opp_big_blunder_playing_mid,
    gs.has_miss_opp_big_blunder_playing_late
FROM {{ ref('int_games_stats') }} gs
{% if is_incremental() %}
    WHERE gs.run_timestamp > (
        SELECT MAX(i.run_timestamp)
        FROM {{ this }} i
    )
{% endif %}