{{ config(
    materialized = 'incremental',
    incremental_strategy = 'append',
    post_hook=[
        "CREATE INDEX IF NOT EXISTS idx_{{ this.name }}_log_timestamp ON {{ this }} (log_timestamp)"
    ]
) }}

SELECT
    {{ dbt_utils.generate_surrogate_key(['igs.username']) }} as players_sk,
    {{ dbt_utils.generate_surrogate_key(['igs.uuid', 'igs.username']) }} as games_sk,
    igs.username,
    igs.uuid,
    igs.log_timestamp,
    igs.nb_moves,
    igs.nb_blunder_massive_blunder_playing,
    igs.nb_massive_blunder_playing,
    igs.nb_moves_above_decisive_advantage,
    igs.massive_blunder_move_number_playing,
    igs.nb_throw_playing,
    igs.nb_throw_blunder_playing,
    igs.nb_throw_massive_blunder_playing,
    igs.nb_missed_opportunity_playing,
    igs.nb_missed_opportunity_blunder_playing,
    igs.nb_missed_opportunity_massive_blunder_playing,
    igs.nb_massive_blunder_playing_early,
    igs.nb_blunder_massive_blunder_playing_early,
    igs.nb_missed_opportunity_blunder_playing_early,
    igs.nb_missed_opportunity_massive_blunder_playing_early,
    igs.nb_throw_blunder_playing_early,
    igs.nb_throw_massive_blunder_playing_early,
    igs.nb_massive_blunder_playing_mid,
    igs.nb_blunder_massive_blunder_playing_mid,
    igs.nb_missed_opportunity_blunder_playing_mid,
    igs.nb_missed_opportunity_massive_blunder_playing_mid,
    igs.nb_throw_blunder_playing_mid,
    igs.nb_throw_massive_blunder_playing_mid,
    igs.nb_massive_blunder_playing_late,
    igs.nb_blunder_massive_blunder_playing_late,
    igs.nb_missed_opportunity_blunder_playing_late,
    igs.nb_missed_opportunity_massive_blunder_playing_late,
    igs.nb_throw_blunder_playing_late,
    igs.nb_throw_massive_blunder_playing_late,
    igs.nb_massive_blunder_playing_very_late,
    igs.nb_blunder_massive_blunder_playing_very_late,
    igs.nb_missed_opportunity_blunder_playing_very_late,
    igs.nb_missed_opportunity_massive_blunder_playing_very_late,
    igs.nb_throw_blunder_playing_very_late,
    igs.nb_throw_massive_blunder_playing_very_late,
    igs.nb_throw_opponent,
    igs.nb_throw_blunder_opponent,
    igs.nb_throw_massive_blunder_opponent,
    igs.nb_missed_opportunity_opponent,
    igs.nb_missed_opportunity_blunder_opponent,
    igs.nb_missed_opportunity_massive_blunder_opponent,
    igs.nb_massive_blunder_opponent_early,
    igs.nb_blunder_massive_blunder_opponent_early,
    igs.nb_missed_opportunity_blunder_opponent_early,
    igs.nb_missed_opportunity_massive_blunder_opponent_early,
    igs.nb_throw_blunder_opponent_early,
    igs.nb_throw_massive_blunder_opponent_early,
    igs.nb_massive_blunder_opponent_mid,
    igs.nb_blunder_massive_blunder_opponent_mid,
    igs.nb_missed_opportunity_blunder_opponent_mid,
    igs.nb_missed_opportunity_massive_blunder_opponent_mid,
    igs.nb_throw_blunder_opponent_mid,
    igs.nb_throw_massive_blunder_opponent_mid,
    igs.nb_massive_blunder_opponent_late,
    igs.nb_blunder_massive_blunder_opponent_late,
    igs.nb_missed_opportunity_blunder_opponent_late,
    igs.nb_missed_opportunity_massive_blunder_opponent_late,
    igs.nb_throw_blunder_opponent_late,
    igs.nb_throw_massive_blunder_opponent_late,
    igs.nb_massive_blunder_opponent_very_late,
    igs.nb_blunder_massive_blunder_opponent_very_late,
    igs.nb_missed_opportunity_blunder_opponent_very_late,
    igs.nb_missed_opportunity_massive_blunder_opponent_very_late,
    igs.nb_throw_blunder_opponent_very_late,
    igs.nb_throw_massive_blunder_opponent_very_late,
    igs.first_blunder_massive_blunder_playing_prct_time_remaining,
    igs.first_massive_blunder_playing_prct_time_remaining,
    igs.first_missed_opp_massive_blunder_playing_prct_time_remaining,
    igs.first_throw_massive_blunder_playing_prct_time_remaining,
    igs.prct_time_remaining_playing_early,
    igs.prct_time_remaining_playing_mid,
    igs.prct_time_remaining_playing_late,
    igs.median_score_playing,
    igs.max_score_playing,
    igs.min_score_playing,
    igs.std_score_playing,
    igs.max_score_playing_range,
    igs.max_score_playing_type,
    igs.has_throw_blunder_playing,
    igs.has_throw_blunder_playing_early,
    igs.has_throw_blunder_playing_mid,
    igs.has_throw_blunder_playing_late,
    igs.has_throw_massive_blunder_playing,
    igs.has_throw_massive_blunder_playing_early,
    igs.has_throw_massive_blunder_playing_mid,
    igs.has_throw_massive_blunder_playing_late,
    igs.has_missed_opportunity_blunder_playing,
    igs.has_missed_opportunity_blunder_playing_early,
    igs.has_missed_opportunity_blunder_playing_mid,
    igs.has_missed_opportunity_blunder_playing_late,
    igs.has_missed_opportunity_massive_blunder_playing,
    igs.has_missed_opportunity_massive_blunder_playing_early,
    igs.has_missed_opportunity_massive_blunder_playing_mid,
    igs.has_missed_opportunity_massive_blunder_playing_late
FROM {{ ref('int_games_stats') }} igs
{% if is_incremental() %}
WHERE igs.log_timestamp > (
    SELECT MAX(i.log_timestamp)
    FROM {{ this }} i
)
{% endif %}