name: 'chess_com_bi_pg'
version: '1.0.0'

profile: 'chess_com_bi_pg'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  chess_com_bi_pg:
    intermediate:
      +schema: int
      +materialized: table
