services:
  analytical_db:
    image: postgres:16
    container_name: chess_postgres_container
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - analytical_data:/var/lib/postgresql/data 
    ports:
      - "5433:5432"

  metabase:
    image: metabase/metabase:v0.53.5
    container_name: chess_metabase_container
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - analytical_db

  streamlit:
    image: gabriellegall/chess-com-bi-pg-streamlit:latest
    container_name: chess_streamlit_container
    restart: always
    ports:
      - "8501:8501"
    depends_on:
      - analytical_db
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: analytical_db
      DB_PORT: 5432

  dbt:
    image: gabriellegall/chess-com-bi-pg-dbt:latest
    container_name: chess_dbt_container
    depends_on:
      - analytical_db
    working_dir: /app
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: analytical_db
      DB_PORT: 5432
      HEALTHCHECK_URL: ${HEALTHCHECK_URL}
      HEALTHCHECK_URL_DBT_TEST: ${HEALTHCHECK_URL_DBT_TEST}

  watchtower:
    image: containrrr/watchtower
    container_name: chess_watchtower_container
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_SCHEDULE=0 0 * * * * 
      - TZ=Europe/Paris
    command: chess_dbt_container chess_streamlit_container

volumes:
  analytical_data: