api:
  user_groups:
    friends:
      usernames:
        - piwi100
        - Zundorn
        - leprechess
        - bgdu33
        - quentinusdesbois
        - romainpct
        - gokhvttttgxdddhjkig345
        - yorek99
        - ashutoshkhurana568
        - fluffy128li
        - d0niphan
      start_month: "2010/01"
    default_users:
      usernames:
        - aufhebungja
        - slscharff
        - itsdon3
        - koli8
        - tnvawls
        - tandisco
        - mr_nuke
        - andrew_shapekin
        - esasso
        - arekusu22
        - rjvrush
        - constandean
        - suleiman241081
        - thewiltshirewarrior
        - chesstickles09
        - kekkaki42
        - christrafer
        - zupade
        - rik1409
        - girleidson
        - chessman1ray
        - orlandocrl
        - hdawg94
        - kirillolshansky
        - jonathanhj
        - eliaskaram84
        - melnik63
        - ap0lkmn
        - pjm00
        - ojatemate
        - atak_66
        - torpa1975
        - bondpbond
        - rc_dy
        - justinmahi
        - ana2
        - thierry-l85
        - barevner
        - 1Kalinka
        - AKASH6386
        - flickjazz
        - Bacon_and_Jaegs
        - AsisIsisA
        - aadam178
        - Brewmaoster
        - carlosfds
        - ALMacugay
        - CrazyProfAJ
        - MOHIT_0620
        - Karim30120
        - kishoban
        - AAgkoss
        - alirezanorollahi
      start_month: "2025/04"

postgres:
  schemas:
    chess_com_api:  "stg_chess_com"
    stockfish:      "stg_stockfish"
    games_times:    "stg_times"
  tables:
    stockfish:      "players_games_moves"
    games_times:    "players_games_times"