views:
  - name: v_games

    cubes:
      - join_path: cube_games
        includes:
          - uuid
          - url
          - eco
          - end_time
          - time_class
          - time_control
          - playing_as
          - playing_rating
          - playing_rating_range
          - opponent_rating
          - opponent_rating_range
          - playing_result
          - rated
          - win_rate

      - join_path: cube_games.cube_players
        includes:
          - username_global

      - join_path: cube_games.cube_games_stats
        includes:
          - games_sk
          - nb_moves
          - prct_time_remaining_playing_early
          - prct_time_remaining_playing_mid
          - prct_time_remaining_playing_late
          - has_throw_blunder_playing
          - has_throw_blunder_playing_early
          - has_throw_blunder_playing_mid
          - has_throw_blunder_playing_late
          - has_throw_big_blunder_playing
          - has_throw_big_blunder_playing_early
          - has_throw_big_blunder_playing_mid
          - has_throw_big_blunder_playing_late
          - has_miss_opp_blunder_playing
          - has_miss_opp_blunder_playing_early
          - has_miss_opp_blunder_playing_mid
          - has_miss_opp_blunder_playing_late
          - has_miss_opp_big_blunder_playing
          - has_miss_opp_big_blunder_playing_early
          - has_miss_opp_big_blunder_playing_mid
          - has_miss_opp_big_blunder_playing_late
          - first_blunder_big_blunder_playing_prct_time_remaining
          - first_big_blunder_playing_prct_time_remaining
          - first_miss_opp_big_blunder_playing_prct_time_remaining
          - first_throw_big_blunder_playing_prct_time_remaining
          - score_playing_turn_5
          - score_playing_turn_10
          - score_playing_turn_15
          - score_playing_turn_20
          - score_playing_turn_25
          - score_playing_turn_30
          - score_playing_turn_35
          - score_playing_turn_40
          - score_playing_turn_45
          - score_playing_turn_50
          - max_score_playing_type

      - join_path: cube_games.cube_games_openings
        includes:
          - opening_level_1_name
          - opening_level_2_name
          - opening_level_7_name
          - opener_7_moves
