views:
  - name: v_game_moves

    cubes:
      - join_path: cube_games
        includes:
          - end_time
          - time_class
          - playing_result
          - playing_rating_range

      - join_path: cube_games.cube_players
        includes:
          - username_global

      - join_path: cube_games.cube_game_moves
        includes:
          - move_number
          - game_phase
          - playing_turn_name
          - is_playing_turn
          - miss_category_playing
          - miss_context_playing
          - miss_category_opponent
          - position_status_playing
          - prct_time_remaining
