api:
  usernames:
    # friends
    - piwi100
    - Zundorn
    - leprechess
    - bgdu33
    - quentinusdesbois
    - romainpct
    - gokhvttttgxdddhjkig345
    - yorek99
    - ashutoshkhurana568
    # chess.com:
    - oignons52
    # Reddit users:
    - dapipshark
    - sajmansito
    - beng_16
    - 62westwallaby
    - xn312fx
    - sluciano3
    - glenmsheppard
    - jaebr8
    - max_otto_stierlitz
    - kkgttv
    - chesstrogen
    - typicalplayer11
    - meachumz
    - febar92
    - monksc
    - allem34
    - nadis_z
    - rogerick
    - babystinkboog
    - nyylp844
    - jamesi05
    - somedrewguy
    - voidlr
    - veddntt
    - bonbonfrosch
    - karthik704
    - grosgogtjopie
    - jveitch24
    - playing_in_alg2
    - l46w4ll
  start_month: "2024/01"

postgres:
  schemas:
    chess_com_api:  "stg_chess_com"
    stockfish:      "stg_stockfish"
    games_times:    "stg_times"
  tables:
    stockfish:      "players_games_moves"
    games_times:    "players_games_times"