api:
  usernames:
    - piwi100
    - Zundorn
    - leprechess
    - bgdu33
    - quentinusdesbois
    - romainpct
    - gokhvttttgxdddhjkig345
    - yorek99
    - ashutoshkhurana568
  start_month: "2024/01"

postgres:
  schemas:
    chess_com_api:  "stg_chess_com"
    stockfish:      "stg_stockfish"
    games_times:    "stg_times"
  tables:
    stockfish:      "players_games_moves"
    games_times:    "players_games_times"